travis:
  secure:
    BINSTAR_TOKEN: McXPEgh74Y934v8a29Aa++jXlZ/G+9hCr+u/E6e5dEY9lc7MHywtf9BL0wjfW9vu8sltLrCip24i8X+cHuXd2eX3xTjy2utk4igIkYiZ00AelI0ICOGccKDn1PQ20W31NBL3GrRP9Qky1HjWva4pkJ4WTsyfGli+VfdO9MGtFE+b9CD/UtOPRqNvgS1Myy/ocuUVBvFnGzoHdQpL9uq+7AxdS66vRaFBRiZwymbHNg6/OdOacq627Pgy+pBKKV3OZ78scTyovYUtsG4qfqwt2mjRAxCauxmtKcFj3bBJ+QnadvOHqIESo07orbxwNXO131eUesbrIcpiGWrlfLNUigC2VUtfvcpHAFj629JbyDGP3HbygMmN6jYr6E6WGNt+qA8rq6hv0XgoCkZ8OOxcBfjjeb8LRi6jawUx2W2rvKnS6ZoKuOLxjUKUv0IKWvYFRtPkEcF52Yd9daVYeFDOkcgexJ53Lb5rp8hA3mDRWIK2plnznfiHGdb95X8hAeGXzR0syjJwhRPKNAel0paio0iCt70ZIcJq/3iVlXcEXXpA2OAJZaX3KY+dWNwcvxYBgERK4bVPcqXJNMLFjzSaoALKEf771uKJoyAE7Cl0mkNZRfAAbfcKgMr57M6k6+I/3PzDF4TjW2Z/nX+gvel+UpSKjPtAuXlMDgPBfMg19Js=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
